site_name: SupplyNetPy Documentation
nav:
  - Home: index.md
  - Overview: overview.md
  - SupplyNetPy in 10 Minutes: ten_min.md
  - API reference: api-ref.md
  - About: about.md
theme: readthedocs
plugins:
  - search
  - mkdocstrings