site_name: SupplyNetPy Documentation
nav:
  - Home: index.md
  - SupplyNetPy in 10 Minutes: ten_min.md
  - About: about.md
  - Examples: 
    - Basic: example.md
  - API reference:
    - Introduction: api-reference/api-intro.md
    - Components.core: api-reference/api-ref-core.md
    - Components.logger: api-reference/api-ref-logger.md
    - Components.utilities: api-reference/api-ref-utilities.md
  
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          show_source: false